version: '3.8'

services:
  mysqlContainer:
    image: mysql:8.0
    container_name: mysqlContainer
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: genesis-test-proj
    environment:
      - DATABASE_HOST=mysqlContainer
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=subscribers
    depends_on:
      - mysqlContainer
    ports:
      - "3000:3000"

volumes:
  mysql-data: